version = 1

test_patterns = ["__tests__/**"]

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  environment = [
    "nodejs",
    "jest"
  ]

[[analyzers]]
name = "secrets"

[[analyzers]]
name = "test-coverage"
