name: Test and build

on: push 

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
      - run: npm ci
      - run: npm run lint

      # Jets requires an extra node flag to work with ES modules
      # cf. https://jestjs.io/docs/ecmascript-modules
      - run: NODE_OPTIONS='--experimental-vm-modules' npm run test
